# Generated by Django 5.2.6 on 2025-09-22 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shop_category_alter_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('name', models.CharField()),
                ('brand', models.CharField()),
            ],
        ),
    ]
