# Generated by Django 5.2.6 on 2025-10-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
    ]
